-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 19:03:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

drop database if exists mysql;
create database mysql;
use mysql;

CREATE TABLE Provedor (
    Num_provedor INT NOT NULL,
    idProvedor INT NOT NULL,
    Nombre VARCHAR(45) NOT NULL,
    Num_tel VARCHAR(45) NOT NULL,
    Apellido VARCHAR(45) NULL,
    Mail VARCHAR(45) NULL,
    tipo_proveedor VARCHAR(45) NULL,
  PRIMARY KEY (Num_Provedor)
);



CREATE TABLE Orden_provedor (
    Num_orden INT NOT NULL,
    Id_Orden_provedor INT NOT NULL,
    precio_Orden_provedor FLOAT NULL,
    cantidad_kg FLOAT NULL,
    fecha DATE NULL,
    Cuit INT NULL,
    Lugar_entrega VARCHAR(45) NULL,
    Provedor INT NOT NULL,
  PRIMARY KEY (Num_orden),
  INDEX fk_Orden_provedor (Provedor ASC),
  CONSTRAINT fk_Orden_provedor
    FOREIGN KEY (Provedor)
    REFERENCES Provedor (Num_provedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Producto (
    Num_producto INT NOT NULL,
    idProducto INT NOT NULL,
    Nombre VARCHAR(45) NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Precio DOUBLE NOT NULL,
    Fecha_vencimiento DATE NOT NULL,
    Cantidad_kg FLOAT NULL,
    Orden_producto_Num_orden INT NOT NULL,
  PRIMARY KEY (Num_producto),
  UNIQUE INDEX idProducto_UNIQUE (idProducto ASC),
  INDEX fk_Producto_Orden_producto1_idx (Orden_producto_Num_orden ASC),
  CONSTRAINT fk_Producto_Orden_producto1
    FOREIGN KEY (Orden_producto_Num_orden)
    REFERENCES Orden_provedor (Num_orden)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Cliente (
    num_Cliente INT NOT NULL,
    idCliente INT NOT NULL,
    Nombre VARCHAR(45) NOT NULL,
    Apellido VARCHAR(45) NOT NULL,
    Telefono VARCHAR(45) NOT NULL,
    Direccion VARCHAR(45) NOT NULL,
  PRIMARY KEY (num_Cliente),
  UNIQUE INDEX num_Cliente_UNIQUE (num_Cliente ASC)
);




CREATE TABLE Contacto_Emergencia (
    numContacto VARCHAR(45) NOT NULL,
    idContacto INT NOT NULL,
    Nombre VARCHAR(45) NULL,
    Apellido VARCHAR(45) NULL,
    Telefono VARCHAR(45) NULL,
    Parentesco VARCHAR(45) NULL,
    Mail VARCHAR(45) NULL,
    Domicilio VARCHAR(45) NULL,
    Trabajo_tel VARCHAR(45) NULL,
    Ciudad VARCHAR(45) NULL,
  PRIMARY KEY (numContacto),
  UNIQUE INDEX numContacto_UNIQUE (numContacto ASC)
);




CREATE TABLE Empleado (
    Num_empleado INT NOT NULL,
    idempleado INT NOT NULL,
    DNI INT NOT NULL,
    Puesto VARCHAR(45) NOT NULL,
    Horario VARCHAR(45) NOT NULL,
    Sueldo DOUBLE NOT NULL,
    Nombre VARCHAR(45) NULL,
    Apellido VARCHAR(45) NULL,
    Direccion VARCHAR(45) NULL,
    Telefono VARCHAR(45) NULL,
    Numero_emergencia VARCHAR(45) NULL,
    Obra_social VARCHAR(45) NULL,
    Num_obra_social VARCHAR(45) NULL,
    Contacto_Emergencia_numContacto VARCHAR(45) NOT NULL,
  PRIMARY KEY (Num_empleado),
  UNIQUE INDEX Num_empleado_UNIQUE (Num_empleado ASC),
  INDEX fk_Empleado_Contacto_Emergencia1_idx (Contacto_Emergencia_numContacto ASC),
  CONSTRAINT fk_Empleado_Contacto_Emergencia1
    FOREIGN KEY (Contacto_Emergencia_numContacto)
    REFERENCES Contacto_Emergencia (numContacto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Factura (
    Num_factura INT NOT NULL,
    Tipo_factura VARCHAR(45) NOT NULL,
    Fecha DATE NOT NULL,
    Total FLOAT NOT NULL,
    Medio_de_pago VARCHAR(45) NOT NULL,
    idFactura INT NOT NULL,
  PRIMARY KEY (Num_factura),
  UNIQUE INDEX Num_factura_UNIQUE (Num_factura ASC)
);




CREATE TABLE Pedido (
    numPedido INT NOT NULL,
    idPedido INT NOT NULL,
    Fecha DATETIME NOT NULL,
    descripcion VARCHAR(45) NOT NULL,
    tipoPedido VARCHAR(45) NOT NULL,
    Cliente INT NOT NULL,
    Empleado INT NOT NULL,
  PRIMARY KEY (numPedido),
  UNIQUE INDEX numPedido_UNIQUE (numPedido ASC),
  INDEX fk_Pedido_Cliente1_idx (Cliente ASC),
  INDEX fk_Pedido_Empleado1_idx (Empleado ASC),
  CONSTRAINT fk_Pedido_Cliente1
    FOREIGN KEY (Cliente)
    REFERENCES Cliente (num_Cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Empleado1
    FOREIGN KEY (Empleado)
    REFERENCES Empleado (Num_empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Detalle_Pedido (
    Cantidad_productos INT NOT NULL,
    Subtotal DOUBLE NULL,
    IVA DOUBLE NULL,
    Precio_unitario DOUBLE NULL,
    Factura_Num_factura INT NOT NULL,
    Pedido INT NOT NULL,
  PRIMARY KEY (Factura_Num_factura, Pedido),
  INDEX fk_Detalle_Pedido_Pedido1_idx (Pedido ASC),
  CONSTRAINT fk_Detalle_Pedido_Factura1
    FOREIGN KEY (Factura_Num_factura)
    REFERENCES Factura (Num_factura)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Detalle_Pedido_Pedido1
    FOREIGN KEY (Pedido)
    REFERENCES Pedido (numPedido)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Locales (
    numLocal INT NOT NULL,
    idLocal INT NULL,
    direccion VARCHAR(45) NULL,
    apertura TIME NULL,
    cierre TIME NULL,
    nombre_fanasioso VARCHAR(45) NULL,
    cant_empleados INT NULL,
    ciudad VARCHAR(45) NULL,
    pais VARCHAR(45) NULL,
    fecha_apertura DATETIME NULL,
    descripcio VARCHAR(45) NULL,
    telefono VARCHAR(45) NULL,
  PRIMARY KEY (numLocal)
);




CREATE TABLE Gerente (
    numGerente INT NOT NULL,
    idGerente INT NOT NULL,
    Empleado INT NOT NULL,
    Local_numLocal INT NOT NULL,
  PRIMARY KEY (numGerente, Local_numLocal),
  UNIQUE INDEX numGerente_UNIQUE (numGerente ASC),
  INDEX fk_Gerente_Empleado1_idx (Empleado ASC),
  INDEX fk_Gerente_Local_idx (Local_numLocal ASC),
  CONSTRAINT fk_Gerente_Empleado1
    FOREIGN KEY (Empleado)
    REFERENCES Empleado (Num_empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Gerente_Local
    FOREIGN KEY (Local_numLocal)
    REFERENCES Locales (numLocal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Ingredientes (
    Num_ingrediente INT NOT NULL,
    Cantidad_kg FLOAT NOT NULL,
    Nombre VARCHAR(45) NOT NULL,
    idIngrediente VARCHAR(45) NOT NULL,
    Pedido INT NOT NULL,
    Producto INT NOT NULL,
  PRIMARY KEY (Num_ingrediente, Pedido, Producto),
  INDEX fk_Ingredientes_Pedido1_idx (Pedido ASC),
  INDEX fk_Ingredientes_Producto1_idx (Producto ASC),
  CONSTRAINT fk_Ingredientes_Pedido
    FOREIGN KEY (Pedido)
    REFERENCES Pedido (numPedido)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Ingredientes_Producto
    FOREIGN KEY (Producto)
    REFERENCES Producto (Num_producto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Facturas_local (
    numFactura INT NOT NULL,
    Gastos FLOAT NOT NULL,
    Ingresos FLOAT NOT NULL,
    fechaFactura DATE NOT NULL,
    id_factura VARCHAR(45) NOT NULL,
    Local_numLocal INT NOT NULL,
  PRIMARY KEY (numFactura, Local_numLocal),
  INDEX fk_Facturas_local_Local1_idx (Local_numLocal ASC),
  CONSTRAINT fk_Facturas_local_Local
    FOREIGN KEY (Local_numLocal)
    REFERENCES Locales (numLocal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Licensias (
    numLicensias INT NOT NULL,
    idLicensias VARCHAR(45) NULL,
    Tipolicensia VARCHAR(45) NULL,
    duracion DATE NULL,
    descripcion VARCHAR(45) NULL,
    fechaInicio DATE NULL,
    fechaFinal DATE NULL,
    razon VARCHAR(50) NULL,
    Licensiascol VARCHAR(45) NULL,
    Empleado INT NOT NULL,
  PRIMARY KEY (numLicensias, Empleado),
  INDEX fk_Licensias_Empleado_idx (Empleado ASC),
  CONSTRAINT fk_Licensias_Empleado
    FOREIGN KEY (Empleado)
    REFERENCES Empleado (Num_empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Presentismo (
    NumPresentismo INT NOT NULL,
    idPresentismo INT NOT NULL,
    asistencias INT NOT NULL,
    suspenciones INT NOT NULL,
    Licensias INT NOT NULL,
    Empleado INT NOT NULL,
  PRIMARY KEY (NumPresentismo, Licensias, Empleado),
  INDEX fk_Presentismo_Licensias_idx (Licensias ASC),
  INDEX fk_Presentismo_Empleado_idx (Empleado ASC),
  CONSTRAINT fk_Presentismo_Licensias
    FOREIGN KEY (Licensias)
    REFERENCES Licensias (numLicensias)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Presentismo_Empleado
    FOREIGN KEY (Empleado)
    REFERENCES Empleado (Num_empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Faltas (
    numFaltas INT NOT NULL,
    idFaltas INT NOT NULL,
    faltas INT NOT NULL,
    llegadas_tarde INT NOT NULL,
    razonFalta VARCHAR(45) NOT NULL,
    gravedad VARCHAR(45) NOT NULL,
    Empleado INT NOT NULL,
  PRIMARY KEY (numFaltas),
  INDEX fk_Faltas_Empleado_idx (Empleado ASC),
  CONSTRAINT fk_Faltas_Empleado
    FOREIGN KEY (Empleado)
    REFERENCES Empleado (Num_empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);




CREATE TABLE Maquinaria (
    numMaquinaria INT NOT NULL,
    idMaquinaria INT NULL,
    tipoMaquina VARCHAR(45) NULL,
    Marca VARCHAR(45) NULL,
    Modelo VARCHAR(45) NULL,
    Color VARCHAR(45) NULL,
    Peso_kg FLOAT NULL,
    Descripcion VARCHAR(45) NULL,
    Garantia DATE NULL,
    ultimo_Mantenimiento DATE NULL,
    Maquinariacol VARCHAR(45) NULL,
    Local_numLocal INT NOT NULL,
    Provedor INT NOT NULL,
  PRIMARY KEY (numMaquinaria),
  INDEX fk_Maquinaria_Local_idx (Local_numLocal ASC),
  INDEX fk_Maquinaria_Provedor_idx (Provedor ASC),
  CONSTRAINT fk_Maquinaria_Local
    FOREIGN KEY (Local_numLocal)
    REFERENCES Locales (numLocal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Maquinaria_Provedor
    FOREIGN KEY (Provedor)
    REFERENCES Provedor (Num_provedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;